project:
  type: website

website:
  title: "Project Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: code.qmd
        text: Code
      - href: data.qmd
        text: Data
      - href: introduction.qmd
        text: Introduction
      - href: data_garther.qmd
        text: Data Garther
      - href: data_cleaning.qmd
        text: Data Cleaning
      - href: data_exploration.ipynb
        text: Data Exploration
      - text: Naive Bayes
        menu:
          - text: Naive Bayes Introduction
            href: naive_bayes.qmd
          - text: Naive Bayes on Record Data
            href: naive_bayes_record.ipynb
          - text: Naive Bayes on Text Data
            href: nb_text.ipynb
      - href: clustering.ipynb
        text: Clustering
      - href: dimensionality_reduction.ipynb
        text: Dimensionality Reduction
      - href: dicision_tree.qmd
        text: Decision Tree
      - href: arm.qmd
        text: ARM
      - href: conclusion.qmd
        text: Conclusion

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

bibliography: references.bib



