---
title: "About Me"
---

## Self Introduction
My name is Yang Tianze, currently studying in Georgetown University’s DSAN Master program. I graduate from both the University of South Australia with a Bachelor’s degree in Software Engineering (Honors) and Xi’an University of Architecture and Technology in Computer Science. 

For my internship experiences, I worked for ZhiguangHailian Big Data Technology Co., LTD, and Zhihu Inc. During these internships, I improved my skills in data processing, software development, and machine learning in real world practice. At ZhiguangHailian, I developed a Python algorithm to determine GPS coordinates from textual geographic locations and determine which district it belongs to.  At Zhihu Inc., I was heavily involved into data cleaning, especially for creating training and testing set for their Large Language Model. I also had a chance to use that model create application to detect adult contents on their website. 

I also have some academic projects. I’ve worked on projects like the SA Opportunity Atlas under the guidance of Justin Anderson from MIT for my bachelor graduation. Additionally, I researched the application of AI in medical treatment under the mentorship of Dianbo Liu from Harvard University. These projects allowed me to practice a wide range of both frontend and machine learning skills. 
In terms of programming skills, I am proficient in programming languages Python, Java and Swift. I have experience with web development tools such as .NET, C#, Bootstrap, and Angular JS. My expertise also extends to data analysis with tools like SQL and R, and I am familiar with distributed systems like Apache Hadoop.

## Education
2018 - 2020: Xi'an University of Architecture and Technology, Xi'an, China
Degree: Bachelor of Computer Science

2020 - 2022: University of South Australia, Adelaide, SA
Degree: Bachelor of Software Engineering (Honors)

2023 - now: Georgetonw University, Washington, DC
Program: Master of Science in Data Science and Analytics

## Academic Interests

- Computer Science and related diciplines
- Machine Learning
- Data Scinece
- Also want to learn more about biology if I could in the future.
